### PR TITLE
Match packages using the local GOROOT and GOPATH.

### PR DESCRIPTION
**Pull request by crawshaw**
This has little measurable performance impact, as only the packages with
candidate names are parsed.

ok      github.com/bradfitz/goimports 0.099s

### CODE REVIEW

**Comment by crawshaw** [comment]
I believe the bug is fixed.

**Comment by fatih** [comment]
Confirmed, works well now. But there is another problem (which is not related with this mr). Basically it removes this line:

```
"github.com/op/go-logging"
```

I was using it like `var log = logging.MustGetLogger("myserver")`. Thanks for your efforts.

**Comment by crawshaw** [comment]
Yes, that's still listed as a caveat in the README. If you write

```
    import logging "github.com/op/go-logging"
```

then goimports will leave it alone.

**Comment by fatih** [comment]
Ok thanks for the info. I guess that is not predictable? Or it is diffuclt to implement? (just curious)

**Comment by crawshaw** [comment]
It's possible, just not high on my list as the codebases I work on exclusively use the base of the import path as the package name.

To do it, goimports would start by parsing each of the packages currently imported and extracting their package names (the go/build package does the hard work). It's not too hard.

**Pull request merged**
